In [1]:
#Mohanapriya G S

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import matplotlib.pyplot as plt

In [5]:
mp=pd.read_csv("C:/Users/ELCOT/Documents/sales_data.csv")

In [7]:
print(mp)

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [15]:
mp.loc[0:19]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
6      1055  2026-01-03  Headphones  Accessories         1        150
7      1020  2026-01-03      Laptop  Electronics         1       1200
8      1082  2026-01-03  Smartphone  Electronics         4        800
9      1085  2026-01-04      Laptop  Electronics         1       1200
10     1088  2026-01-04      Tablet  Electronics         4        450
11     1094  2026-01-04      Tablet  Electronics         4        450
12     1017  2026-01-04  Smartwatch  Accessories         3        250
13     1063  2026-01-04  Smartwatch  Accessories         4        250
14     1056  2026-01-05  Smartwatch  Accessories         4        250
15     1091  2026-01-06  Smartwatch  Accessories         4        250
16     1027  2026-01-06      Tablet  Electronics         2        450
17     1061  2026-01-07  Headphones  Accessories         3        150
18     1058  2026-01-07      Laptop  Electronics         2       1200
19     1077  2026-01-07  Headphones  Accessories         2        150

In [13]:
mp.iloc[0:10,0:5]

   OrderID        Date     Product     Category  Quantity
0     1031  2026-01-01  Smartphone  Electronics         3
1     1100  2026-01-02  Headphones  Accessories         2
2     1028  2026-01-02      Laptop  Electronics         2
3     1089  2026-01-02      Laptop  Electronics         3
4     1023  2026-01-02      Tablet  Electronics         4
5     1072  2026-01-02  Smartphone  Electronics         4
6     1055  2026-01-03  Headphones  Accessories         1
7     1020  2026-01-03      Laptop  Electronics         1
8     1082  2026-01-03  Smartphone  Electronics         4
9     1085  2026-01-04      Laptop  Electronics         1

In [18]:
mp[mp["OrderID"]>1000]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [23]:
mp[mp["Quantity"]<2]

    OrderID        Date     Product     Category  Quantity  UnitPrice
6      1055  2026-01-03  Headphones  Accessories         1        150
7      1020  2026-01-03      Laptop  Electronics         1       1200
9      1085  2026-01-04      Laptop  Electronics         1       1200
34     1051  2026-01-12      Tablet  Electronics         1        450
35     1032  2026-01-12  Smartphone  Electronics         1        800
50     1086  2026-01-18      Laptop  Electronics         1       1200
61     1008  2026-01-21  Smartwatch  Accessories         1        250
63     1022  2026-01-21  Headphones  Accessories         1        150
65     1034  2026-01-22  Headphones  Accessories         1        150
66     1021  2026-01-22      Laptop  Electronics         1       1200
67     1095  2026-01-22      Laptop  Electronics         1       1200
68     1092  2026-01-22      Laptop  Electronics         1       1200
70     1012  2026-01-23  Headphones  Accessories         1        150
72     1024  2026-01-24      Tablet  Electronics         1        450
76     1064  2026-01-25      Tablet  Electronics         1        450
77     1070  2026-01-26  Headphones  Accessories         1        150
81     1010  2026-01-26      Laptop  Electronics         1       1200
82     1039  2026-01-27  Smartwatch  Accessories         1        250
85     1065  2026-01-28  Smartwatch  Accessories         1        250
92     1096  2026-01-29  Smartwatch  Accessories         1        250
93     1035  2026-01-29      Laptop  Electronics         1       1200
95     1026  2026-01-30      Tablet  Electronics         1        450

In [29]:
mp[mp["UnitPrice"]>=1000]

    OrderID        Date Product     Category  Quantity  UnitPrice
2      1028  2026-01-02  Laptop  Electronics         2       1200
3      1089  2026-01-02  Laptop  Electronics         3       1200
7      1020  2026-01-03  Laptop  Electronics         1       1200
9      1085  2026-01-04  Laptop  Electronics         1       1200
18     1058  2026-01-07  Laptop  Electronics         2       1200
23     1018  2026-01-08  Laptop  Electronics         2       1200
24     1087  2026-01-08  Laptop  Electronics         4       1200
36     1025  2026-01-12  Laptop  Electronics         3       1200
42     1048  2026-01-15  Laptop  Electronics         3       1200
43     1004  2026-01-15  Laptop  Electronics         2       1200
46     1044  2026-01-16  Laptop  Electronics         4       1200
47     1038  2026-01-17  Laptop  Electronics         2       1200
48     1084  2026-01-17  Laptop  Electronics         4       1200
50     1086  2026-01-18  Laptop  Electronics         1       1200
51     1097  2026-01-18  Laptop  Electronics         2       1200
66     1021  2026-01-22  Laptop  Electronics         1       1200
67     1095  2026-01-22  Laptop  Electronics         1       1200
68     1092  2026-01-22  Laptop  Electronics         1       1200
69     1052  2026-01-23  Laptop  Electronics         3       1200
71     1015  2026-01-24  Laptop  Electronics         4       1200
73     1019  2026-01-24  Laptop  Electronics         3       1200
78     1033  2026-01-26  Laptop  Electronics         4       1200
81     1010  2026-01-26  Laptop  Electronics         1       1200
87     1074  2026-01-28  Laptop  Electronics         3       1200
93     1035  2026-01-29  Laptop  Electronics         1       1200

In [33]:
mp[mp["OrderID"]<=1500]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [38]:
mp[(mp["Quantity"]>2) & (mp["UnitPrice"]>800)]

    OrderID        Date Product     Category  Quantity  UnitPrice
3      1089  2026-01-02  Laptop  Electronics         3       1200
24     1087  2026-01-08  Laptop  Electronics         4       1200
36     1025  2026-01-12  Laptop  Electronics         3       1200
42     1048  2026-01-15  Laptop  Electronics         3       1200
46     1044  2026-01-16  Laptop  Electronics         4       1200
48     1084  2026-01-17  Laptop  Electronics         4       1200
69     1052  2026-01-23  Laptop  Electronics         3       1200
71     1015  2026-01-24  Laptop  Electronics         4       1200
73     1019  2026-01-24  Laptop  Electronics         3       1200
78     1033  2026-01-26  Laptop  Electronics         4       1200
87     1074  2026-01-28  Laptop  Electronics         3       1200

In [40]:
mp[(mp["Quantity"]>2) | (mp["UnitPrice"]>10000)]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
8      1082  2026-01-03  Smartphone  Electronics         4        800
10     1088  2026-01-04      Tablet  Electronics         4        450
11     1094  2026-01-04      Tablet  Electronics         4        450
12     1017  2026-01-04  Smartwatch  Accessories         3        250
13     1063  2026-01-04  Smartwatch  Accessories         4        250
14     1056  2026-01-05  Smartwatch  Accessories         4        250
15     1091  2026-01-06  Smartwatch  Accessories         4        250
17     1061  2026-01-07  Headphones  Accessories         3        150
20     1001  2026-01-07  Smartphone  Electronics         4        800
21     1009  2026-01-07  Smartphone  Electronics         4        800
22     1080  2026-01-08  Headphones  Accessories         3        150
24     1087  2026-01-08      Laptop  Electronics         4       1200
25     1006  2026-01-08  Smartwatch  Accessories         4        250
26     1060  2026-01-09  Smartwatch  Accessories         3        250
27     1069  2026-01-09      Tablet  Electronics         4        450
28     1093  2026-01-10      Tablet  Electronics         3        450
30     1014  2026-01-11  Smartwatch  Accessories         4        250
31     1005  2026-01-11  Smartwatch  Accessories         4        250
33     1036  2026-01-12  Headphones  Accessories         3        150
36     1025  2026-01-12      Laptop  Electronics         3       1200
37     1099  2026-01-12  Smartphone  Electronics         3        800
38     1078  2026-01-12  Headphones  Accessories         3        150
39     1083  2026-01-14  Headphones  Accessories         3        150
40     1066  2026-01-14  Headphones  Accessories         4        150
41     1081  2026-01-15      Tablet  Electronics         4        450
42     1048  2026-01-15      Laptop  Electronics         3       1200
44     1045  2026-01-15      Tablet  Electronics         3        450
45     1075  2026-01-15  Smartwatch  Accessories         4        250
46     1044  2026-01-16      Laptop  Electronics         4       1200
48     1084  2026-01-17      Laptop  Electronics         4       1200
49     1062  2026-01-18  Smartwatch  Accessories         4        250
52     1067  2026-01-18  Smartwatch  Accessories         3        250
55     1050  2026-01-19  Smartphone  Electronics         3        800
57     1002  2026-01-20  Headphones  Accessories         3        150
58     1073  2026-01-20  Smartwatch  Accessories         4        250
62     1071  2026-01-21  Smartphone  Electronics         3        800
69     1052  2026-01-23      Laptop  Electronics         3       1200
71     1015  2026-01-24      Laptop  Electronics         4       1200
73     1019  2026-01-24      Laptop  Electronics         3       1200
74     1054  2026-01-25  Smartphone  Electronics         4        800
78     1033  2026-01-26      Laptop  Electronics         4       1200
80     1098  2026-01-26      Tablet  Electronics         3        450
83     1040  2026-01-27      Tablet  Electronics         4        450
84     1029  2026-01-28      Tablet  Electronics         4        450
86     1076  2026-01-28  Headphones  Accessories         3        150
87     1074  2026-01-28      Laptop  Electronics         3       1200
88     1042  2026-01-28      Tablet  Electronics         4        450
90     1079  2026-01-29  Headphones  Accessories         3        150
91     1003  2026-01-29  Headphones  Accessories         3        150
94     1007  2026-01-29  Smartphone  Electronics         4        800
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

In [41]:
mp[~(mp["Quantity"]>100)]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [43]:
mp.sort_values("Category")

    OrderID        Date     Product     Category  Quantity  UnitPrice
49     1062  2026-01-18  Smartwatch  Accessories         4        250
82     1039  2026-01-27  Smartwatch  Accessories         1        250
29     1041  2026-01-10  Headphones  Accessories         2        150
30     1014  2026-01-11  Smartwatch  Accessories         4        250
64     1059  2026-01-21  Headphones  Accessories         2        150
..      ...         ...         ...          ...       ...        ...
37     1099  2026-01-12  Smartphone  Electronics         3        800
36     1025  2026-01-12      Laptop  Electronics         3       1200
35     1032  2026-01-12  Smartphone  Electronics         1        800
44     1045  2026-01-15      Tablet  Electronics         3        450
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [44]:
mp.sort_values("Category",ascending=False)

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
37     1099  2026-01-12  Smartphone  Electronics         3        800
69     1052  2026-01-23      Laptop  Electronics         3       1200
68     1092  2026-01-22      Laptop  Electronics         1       1200
67     1095  2026-01-22      Laptop  Electronics         1       1200
..      ...         ...         ...          ...       ...        ...
49     1062  2026-01-18  Smartwatch  Accessories         4        250
17     1061  2026-01-07  Headphones  Accessories         3        150
29     1041  2026-01-10  Headphones  Accessories         2        150
15     1091  2026-01-06  Smartwatch  Accessories         4        250
77     1070  2026-01-26  Headphones  Accessories         1        150

[100 rows x 6 columns]

In [46]:
mp.sort_values(by=["Category","Product"], ascending=[True,False])

    OrderID        Date     Product     Category  Quantity  UnitPrice
12     1017  2026-01-04  Smartwatch  Accessories         3        250
13     1063  2026-01-04  Smartwatch  Accessories         4        250
14     1056  2026-01-05  Smartwatch  Accessories         4        250
15     1091  2026-01-06  Smartwatch  Accessories         4        250
25     1006  2026-01-08  Smartwatch  Accessories         4        250
..      ...         ...         ...          ...       ...        ...
73     1019  2026-01-24      Laptop  Electronics         3       1200
78     1033  2026-01-26      Laptop  Electronics         4       1200
81     1010  2026-01-26      Laptop  Electronics         1       1200
87     1074  2026-01-28      Laptop  Electronics         3       1200
93     1035  2026-01-29      Laptop  Electronics         1       1200

[100 rows x 6 columns]

In [50]:
mp["Data"]=mp["UnitPrice"]*mp["OrderID"]
print(mp)

    OrderID        Date     Product     Category  Quantity  UnitPrice     Data
0      1031  2026-01-01  Smartphone  Electronics         3        800   824800
1      1100  2026-01-02  Headphones  Accessories         2        150   165000
2      1028  2026-01-02      Laptop  Electronics         2       1200  1233600
3      1089  2026-01-02      Laptop  Electronics         3       1200  1306800
4      1023  2026-01-02      Tablet  Electronics         4        450   460350
..      ...         ...         ...          ...       ...        ...      ...
95     1026  2026-01-30      Tablet  Electronics         1        450   461700
96     1090  2026-01-30  Headphones  Accessories         2        150   163500
97     1049  2026-01-30  Smartwatch  Accessories         4        250   262250
98     1046  2026-01-30  Smartwatch  Accessories         4        250   261500
99     1047  2026-01-30      Tablet  Electronics         3        450   471150

[100 rows x 7 columns]

In [51]:
mp.head()

   OrderID        Date     Product     Category  Quantity  UnitPrice     Data
0     1031  2026-01-01  Smartphone  Electronics         3        800   824800
1     1100  2026-01-02  Headphones  Accessories         2        150   165000
2     1028  2026-01-02      Laptop  Electronics         2       1200  1233600
3     1089  2026-01-02      Laptop  Electronics         3       1200  1306800
4     1023  2026-01-02      Tablet  Electronics         4        450   460350

In [52]:
mp["Data"]=mp["Quantity"]+mp["UnitPrice"]
print(mp)

    OrderID        Date     Product     Category  Quantity  UnitPrice  Data
0      1031  2026-01-01  Smartphone  Electronics         3        800   803
1      1100  2026-01-02  Headphones  Accessories         2        150   152
2      1028  2026-01-02      Laptop  Electronics         2       1200  1202
3      1089  2026-01-02      Laptop  Electronics         3       1200  1203
4      1023  2026-01-02      Tablet  Electronics         4        450   454
..      ...         ...         ...          ...       ...        ...   ...
95     1026  2026-01-30      Tablet  Electronics         1        450   451
96     1090  2026-01-30  Headphones  Accessories         2        150   152
97     1049  2026-01-30  Smartwatch  Accessories         4        250   254
98     1046  2026-01-30  Smartwatch  Accessories         4        250   254
99     1047  2026-01-30      Tablet  Electronics         3        450   453

[100 rows x 7 columns]

In [53]:
mp.tail()

    OrderID        Date     Product     Category  Quantity  UnitPrice  Data
95     1026  2026-01-30      Tablet  Electronics         1        450   451
96     1090  2026-01-30  Headphones  Accessories         2        150   152
97     1049  2026-01-30  Smartwatch  Accessories         4        250   254
98     1046  2026-01-30  Smartwatch  Accessories         4        250   254
99     1047  2026-01-30      Tablet  Electronics         3        450   453

In [54]:
mp.groupby("OrderID")["Data"].min()

OrderID
1001     804
1002     153
1003     153
1004    1202
1005     254
        ...
1096     251
1097    1202
1098     453
1099     803
1100     152
Name: Data, Length: 100, dtype: int64

In [55]:
mp.groupby("Date")["Data"].max()

Date
2026-01-01     803
2026-01-02    1203
2026-01-03    1201
2026-01-04    1201
2026-01-05     254
2026-01-06     452
2026-01-07    1202
2026-01-08    1204
2026-01-09     454
2026-01-10     453
2026-01-11     254
2026-01-12    1203
2026-01-14     154
2026-01-15    1203
2026-01-16    1204
2026-01-17    1204
2026-01-18    1202
2026-01-19     803
2026-01-20     802
2026-01-21     803
2026-01-22    1201
2026-01-23    1203
2026-01-24    1204
2026-01-25     804
2026-01-26    1204
2026-01-27     454
2026-01-28    1203
2026-01-29    1201
2026-01-30     453
Name: Data, dtype: int64

In [56]:
mp.groupby("Product")["Data"].sum()

Product
Headphones     3350
Laptop        30058
Smartphone    10441
Smartwatch     5061
Tablet         9056
Name: Data, dtype: int64

In [57]:
mp.groupby("Category")["Data"].mean()

Category
Accessories    200.261905
Electronics    854.396552
Name: Data, dtype: float64

In [60]:
mp.groupby("Quantity")["Data"].count()

Quantity
1    22
2    21
3    26
4    31
Name: Data, dtype: int64

In [62]:
mp.groupby("UnitPrice")["Data"].std()

UnitPrice
150     0.882735
250     1.234376
450     1.196486
800     0.987096
1200    1.144552
Name: Data, dtype: float64

In [70]:
mp.groupby(["OrderID","Date","Category","Product","Quantity","UnitPrice"])["Data"].agg(["min","max","sum","mean","count","std"])

,,,,,,min,max,sum,mean,count,std
OrderID,Date,Category,Product,Quantity,UnitPrice,,,,,,
1001,2026-01-07,Electronics,Smartphone,4,800,804,804,804,804.0,1,NaN
1002,2026-01-20,Accessories,Headphones,3,150,153,153,153,153.0,1,NaN
1003,2026-01-29,Accessories,Headphones,3,150,153,153,153,153.0,1,NaN
1004,2026-01-15,Electronics,Laptop,2,1200,1202,1202,1202,1202.0,1,NaN
1005,2026-01-11,Accessories,Smartwatch,4,250,254,254,254,254.0,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1096,2026-01-29,Accessories,Smartwatch,1,250,251,251,251,251.0,1,NaN
1097,2026-01-18,Electronics,Laptop,2,1200,1202,1202,1202,1202.0,1,NaN
1098,2026-01-26,Electronics,Tablet,3,450,453,453,453,453.0,1,NaN
1099,2026-01-12,Electronics,Smartphone,3,800,803,803,803,803.0,1,NaN
1100,2026-01-02,Accessories,Headphones,2,150,152,152,152,152.0,1,NaN

In [71]:
mp.groupby("Product")["Data"].agg(["sum","mean","min","max","count","std"])

              sum         mean   min   max  count       std
Product
Headphones   3350   152.272727   151   154     22  0.882735
Laptop      30058  1202.320000  1201  1204     25  1.144552
Smartphone  10441   803.153846   801   804     13  0.987096
Smartwatch   5061   253.050000   251   254     20  1.234376
Tablet       9056   452.800000   451   454     20  1.196486